[package]
name = "yarray"
version = "0.1.0"
authors = ["Lawson Fulton <lawsonfulton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
